### PR TITLE
Brno

### PR DESCRIPTION
**Pull request by honzajavorek**
Added:
- Brno guide from @michalkasparek
- My guide how to get to Brno
- USE-IT map suggestion
- Some other tips (accommodation, Czech Republic)

Not in this PR:
- Link to the page from menu (preferable label: "Brno")
- Mobile version of CSS

Closes https://github.com/pyvec/cz.pycon.org-2016/issues/71

---

I'm not sure having `pyconcz_2016/static_build/` in git is a good idea (it has all the CVS antipatterns in the world: unreadable diffs, merge conflicts, versioned result of compilation, ...), but I'm far from ranting against it at this point.

### CODE REVIEW

**Comment by tricoder42** [comment]
Yes, static_build shouldn't be there, but the other option is to add build step and distribute packages (eggs, wheels), which is a bit more complicated than simple git-based deployment. Regarding merge, when it happen, simply discard it and run `npm run build`...

It could be optimized, but as long as it's not very unconvenient, I don't mind.

**Comment by honzajavorek** [comment]
> Regarding merge, when it happen, simply discard it...

I did exactly that.

> the other option is to add build step and distribute packages

I thought that's the reason.

> it's not very unconvenient

In case there would be higher collaboration rate, I'd strongly argue in favor of more readable diffs. Room for improvement in the future.

> I don't mind

Hence my "I'm far from ranting against it at this point."

**Comment by honzajavorek** [comment]
BTW, regarding the link, I think it can be added as a subsequent PR. If we get this page working without link, we can show it to people and get feedback before actually publishing it.

But it's true there won't be _that_ much room for feedback since I'd like to have this out during Mon the latest 🚀 🕙 😱

**Comment by honzajavorek** [comment]
@tricoder42 I see readability of the PR diff as the biggest problem of the static build included. I tried to mitigate it by isolating it into its own commit so the reviewer can at least go commit by commit when reading and skip the one with build.

**Pull request merged**
